project_id = "nhogzdlphnkqhrqxofor"

[functions.generate-email]
verify_jwt = false

[functions.generate-linkedin]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.analyze-interview]
verify_jwt = false
