import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { Navigation } from "@/components/layout/Navigation";
import { ArrowLeft, Sparkles, RefreshCw, Download, ChevronDown, ChevronUp, Copy } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import { addQuestionsList } from "@/services/questionsService";
import jsPDF from "jspdf";

interface Question {
  id?: number;
  questions_list_id?: number;
  question: string;
  answer: string;
  created_at?: string;
  updated_at?: string;
}

interface LocationState {
  questions?: Question[];
  companyName?: string;
  jobTitle?: string;
  contextSummary?: string;
}

export default function InterviewQuestions() {
  const { toast } = useToast();
  const navigate = useNavigate();
  const location = useLocation();
  const { userId } = useAuth();
  const state = location.state as LocationState | null;

  const [questions, setQuestions] = useState<Question[]>(state?.questions || []);
  const [companyName] = useState(state?.companyName || "");
  const [jobTitle] = useState(state?.jobTitle || "");
  const [contextSummary] = useState(state?.contextSummary || "");
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [loading, setLoading] = useState(!state?.questions);
  const [isGeneratingNew, setIsGeneratingNew] = useState(false);

  useEffect(() => {
    if (!state?.questions) {
      setLoading(false);
    }
  }, [state]);

  const getQuestionKey = (q: Question, index: number) => {
    return q.id ?? q.questions_list_id ?? index;
  };

  const handleGenerateNew = async () => {
    if (!companyName || !jobTitle || !userId) {
      toast({
        title: "Missing Information",
        description: "Company name and job title are required to generate new questions.",
        variant: "destructive",
      });

      navigate("/prepare");
      return;
    }

    setIsGeneratingNew(true);

    try {
      const result = await addQuestionsList(userId, {
        company_name: companyName,
        job_title: jobTitle,
        context_summary: contextSummary,
      });

      const newQuestions = result?.questions || [];

      setQuestions(newQuestions);

      toast({
        title: "New Questions Generated",
        description: `Generated ${newQuestions.length} new questions.`,
      });
    } catch (error) {
      console.error("Error generating new questions:", error);

      toast({
        title: "Error",
        description: "Failed to generate new questions.",
        variant: "destructive",
      });
    } finally {
      setIsGeneratingNew(false);
    }
  };

  const handleCopyQA = async () => {
    const text = questions
      .map((q, i) => {
        return `Q${i + 1}: ${q.question}\nAnswer: ${q.answer}`;
      })
      .join("\n\n");

    await navigator.clipboard.writeText(text);

    toast({
      title: "Copied!",
      description: "Questions and answers copied to clipboard.",
    });
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let yPos = 20;

    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");

    const title =
      companyName && jobTitle
        ? `Interview Questions - ${companyName}`
        : "Interview Questions";

    doc.text(title, margin, yPos);
    yPos += 10;

    if (jobTitle) {
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      doc.text(jobTitle, margin, yPos);
      yPos += 15;
    } else {
      yPos += 10;
    }

    doc.setTextColor(0);

    questions.forEach((q, index) => {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");

      const questionText = `${index + 1}. ${q.question}`;
      const questionLines = doc.splitTextToSize(questionText, contentWidth);

      doc.text(questionLines, margin, yPos);
      yPos += questionLines.length * 5 + 4;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(70);

      const answerText = `Answer: ${q.answer}`;
      const answerLines = doc.splitTextToSize(answerText, contentWidth);

      doc.text(answerLines, margin, yPos);
      yPos += answerLines.length * 5 + 10;

      doc.setTextColor(0);
    });

    const pageCount = doc.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Page ${i} of ${pageCount} - Generated by InterviewAI`, pageWidth / 2, 290, {
        align: "center",
      });
    }

    const safeCompany = companyName ? companyName.replace(/[^a-z0-9]/gi, "_") : "Questions";
    const safeJob = jobTitle ? jobTitle.replace(/[^a-z0-9]/gi, "_") : "";

    doc.save(`Interview_Questions_${safeCompany}${safeJob ? `_${safeJob}` : ""}.pdf`);

    toast({
      title: "Exported!",
      description: "PDF downloaded successfully.",
    });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background">
        <Navigation />
        <main className="pt-24 pb-16 px-4 flex items-center justify-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-page-solid">
      <Navigation />

      <main className="pt-24 pb-16 px-4">
        <div className="max-w-4xl mx-auto">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => window.history.back()}
            className="mb-6"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Button>

          <div className="mb-12 animate-fade-in">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-primary/30 bg-card/50 backdrop-blur-sm mb-6">
              <Sparkles className="w-4 h-4 text-accent" />
              <span className="text-sm font-medium">AI Generated Questions</span>
            </div>

            <h1 className="text-4xl md:text-5xl font-bold mb-4">
              Your Interview Questions
            </h1>

            <p className="text-xl text-muted-foreground">
              {companyName && jobTitle
                ? `${questions.length} questions for ${jobTitle} at ${companyName}`
                : `${questions.length} personalized questions based on your job description`}
            </p>
          </div>

          {questions.length > 0 && (
            <div className="flex flex-wrap gap-4 mb-8">
              <Button
                variant="outline"
                size="lg"
                onClick={handleGenerateNew}
                disabled={isGeneratingNew}
              >
                {isGeneratingNew ? (
                  <>
                    <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <RefreshCw className="w-4 h-4 mr-2" />
                    Generate New
                  </>
                )}
              </Button>

              <Button variant="outline" size="lg" onClick={handleExportPDF}>
                <Download className="w-4 h-4 mr-2" />
                Export
              </Button>

              <Button variant="outline" size="lg" onClick={handleCopyQA}>
                <Copy className="w-4 h-4 mr-2" />
                Copy Q&amp;A
              </Button>
            </div>
          )}

          {questions.length > 0 ? (
            <div className="space-y-6">
              {questions.map((q, index) => {
                const questionKey = getQuestionKey(q, index);
                const isExpanded = expandedId === questionKey;

                return (
                  <Card
                    key={`${questionKey}-${index}`}
                    className="bg-secondary/80 border-primary/20 shadow-card p-6 animate-slide-up hover:shadow-glow transition-smooth"
                    style={{ animationDelay: `${index * 100}ms` }}
                  >
                    <div className="flex items-start justify-between mb-4">
                      <Badge variant="secondary">Question {index + 1}</Badge>
                      <span className="text-muted-foreground text-sm">Q{index + 1}</span>
                    </div>

                    <h3 className="text-lg font-semibold mb-4 leading-relaxed">
                      {q.question}
                    </h3>

                    <div className="mb-4">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => setExpandedId(isExpanded ? null : questionKey)}
                        className="mb-2"
                      >
                        {isExpanded ? (
                          <>
                            <ChevronUp className="w-4 h-4 mr-2" />
                            Hide Suggested Answer
                          </>
                        ) : (
                          <>
                            <ChevronDown className="w-4 h-4 mr-2" />
                            Show Suggested Answer
                          </>
                        )}
                      </Button>

                      {isExpanded && (
                        <div className="bg-primary/5 rounded-lg p-4 animate-slide-up">
                          <p className="text-sm leading-relaxed">{q.answer}</p>
                        </div>
                      )}
                    </div>
                  </Card>
                );
              })}
            </div>
          ) : (
            <Card className="bg-secondary/80 border-primary/20 shadow-card p-12 text-center">
              <Sparkles className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-xl font-semibold mb-2">No Questions Yet</h3>
              <p className="text-muted-foreground mb-6">
                Generate interview questions from a job description to get started.
              </p>
              <Button variant="hero" onClick={() => navigate("/prepare")}>
                Generate Questions
              </Button>
            </Card>
          )}
        </div>
      </main>
    </div>
  );
}
