import jsPDF from "jspdf";

interface Question {
  question: string;
  type?: string;
  difficulty?: string;
  tip?: string;
}

interface InterviewData {
  title: string;
  company?: string | null;
  jobTitle?: string | null;
  questions: Question[];
  createdAt?: string;
}

export const exportQuestionsToPDF = (data: InterviewData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPos = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, margin, yPos);
  yPos += 10;

  // Company and Job Title
  if (data.company || data.jobTitle) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    const subtitle = [data.company, data.jobTitle].filter(Boolean).join(" - ");
    doc.text(subtitle, margin, yPos);
    yPos += 8;
  }

  // Date
  if (data.createdAt) {
    doc.setFontSize(10);
    doc.setTextColor(130);
    doc.text(`Generated: ${new Date(data.createdAt).toLocaleDateString()}`, margin, yPos);
    yPos += 15;
  } else {
    yPos += 10;
  }

  // Questions
  doc.setTextColor(0);
  data.questions.forEach((q, index) => {
    // Check if we need a new page
    if (yPos > 260) {
      doc.addPage();
      yPos = 20;
    }

    // Question number and text
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    const questionText = `${index + 1}. ${q.question}`;
    const lines = doc.splitTextToSize(questionText, contentWidth);
    doc.text(lines, margin, yPos);
    yPos += lines.length * 5 + 3;

    // Type and Difficulty badges
    if (q.type || q.difficulty) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      const badges = [];
      if (q.type) badges.push(`Type: ${q.type}`);
      if (q.difficulty) badges.push(`Difficulty: ${q.difficulty}`);
      doc.text(badges.join("  |  "), margin, yPos);
      yPos += 5;
    }

    // Tip
    if (q.tip) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(80);
      const tipLines = doc.splitTextToSize(`💡 ${q.tip}`, contentWidth);
      doc.text(tipLines, margin, yPos);
      yPos += tipLines.length * 4 + 5;
    }

    doc.setTextColor(0);
    yPos += 5;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by InterviewAI`,
      pageWidth / 2,
      290,
      { align: "center" }
    );
  }

  const filename = `${data.title.replace(/[^a-z0-9]/gi, "_")}_questions.pdf`;
  doc.save(filename);
};

interface ProfileData {
  fullName: string;
  email: string;
  phone?: string;
  location?: string;
  summary?: string;
  skills?: string[];
  experience?: Array<{
    title: string;
    company: string;
    startDate: string;
    endDate?: string;
    description?: string;
  }>;
  education?: Array<{
    degree: string;
    school: string;
    year: string;
  }>;
}

export const exportProfileToPDF = (data: ProfileData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPos = 20;

  // Name
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(data.fullName, margin, yPos);
  yPos += 12;

  // Contact Info
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  const contactInfo = [data.email, data.phone, data.location].filter(Boolean).join("  |  ");
  doc.text(contactInfo, margin, yPos);
  yPos += 15;

  // Summary
  if (data.summary) {
    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("PROFESSIONAL SUMMARY", margin, yPos);
    yPos += 6;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const summaryLines = doc.splitTextToSize(data.summary, contentWidth);
    doc.text(summaryLines, margin, yPos);
    yPos += summaryLines.length * 5 + 10;
  }

  // Skills
  if (data.skills && data.skills.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("SKILLS", margin, yPos);
    yPos += 6;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const skillsText = data.skills.join("  •  ");
    const skillLines = doc.splitTextToSize(skillsText, contentWidth);
    doc.text(skillLines, margin, yPos);
    yPos += skillLines.length * 5 + 10;
  }

  // Experience
  if (data.experience && data.experience.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("EXPERIENCE", margin, yPos);
    yPos += 8;

    data.experience.forEach((exp) => {
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text(exp.title, margin, yPos);
      yPos += 5;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(80);
      const dateRange = exp.endDate ? `${exp.startDate} - ${exp.endDate}` : `${exp.startDate} - Present`;
      doc.text(`${exp.company}  |  ${dateRange}`, margin, yPos);
      yPos += 5;

      if (exp.description) {
        doc.setTextColor(0);
        const descLines = doc.splitTextToSize(exp.description, contentWidth);
        doc.text(descLines, margin, yPos);
        yPos += descLines.length * 4 + 8;
      } else {
        yPos += 5;
      }
    });
    yPos += 5;
  }

  // Education
  if (data.education && data.education.length > 0) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("EDUCATION", margin, yPos);
    yPos += 8;

    data.education.forEach((edu) => {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text(edu.degree, margin, yPos);
      yPos += 5;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(80);
      doc.text(`${edu.school}  |  ${edu.year}`, margin, yPos);
      yPos += 8;
    });
  }

  // Footer
  doc.setTextColor(150);
  doc.setFontSize(8);
  doc.text(
    `Generated by InterviewAI on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    290,
    { align: "center" }
  );

  const filename = `${data.fullName.replace(/[^a-z0-9]/gi, "_")}_Resume.pdf`;
  doc.save(filename);
};
